kind: Service
apiVersion: v1
metadata:
  name: pipeline-1
  labels:
    app: pipeline-1
spec:
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31200
  selector:
    app: pipeline-1
  type: LoadBalancer
